name: CI
# This workflow is triggered on pushes & pull requests
on:
  pull_request:
    branches:
      - main
  push:
    branches: [ main, beta ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
jobs:
  test-frontend:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: chrome --version
      - name: Test Frontend
        run: |
          make frontend-test-coverage-ci
      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: ${{ github.workspace }}/coverage/ngx-fhir/lcov.info
          flags: unittests
          fail_ci_if_error: true
          verbose: true
