name: Deploy Storybook
on:
  push:
    branches: [ main ]
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install and Build
        run: | # Install npm packages and build the Storybook files
          make frontend-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs # The branch the action should deploy to.
          FOLDER: dist-storybook # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: . # The folder that we serve our Storybook files from
